name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - 'feature/*'
    
env:
  MONGO_URI: mongodb+srv://skomantasj:Aitvaras1+@cluster0.rbvmfbp.mongodb.net/superData?retryWrites=true&w=majority&appName=Cluster0
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    unit-testing:
        continue-on-error: true
        name: Unit Testing
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
            node-version: [18, 19, 20]
            exclude:
              - os: windows-latest
                node-version: 18
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install

        - name: Install dotenv
          run: npm install --save dotenv

        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml