name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - 'feature/*'
    
env:
  MONGO_URI: mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD}}@$cluster0.rbvmfbp.mongodb.net/
  PORT: 3000
  


jobs:
    unit-testing:
        continue-on-error: true
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
        - name: Install Dependencies
          run: npm install

        - name: Unit Testing
          continue-on-error: true
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
          
    code-coverage:
      name: Code Coverage
      continue-on-error: true
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Code Coverage
        continue-on-error: true
        run: npm run coverage
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Code-Coverage-result
          path: coverage
          retention-days: 5